### PR TITLE
Update ReSharper.SDK to 2021.2 and Updgrade .NET Framework to v4.7.2

### PR DESCRIPTION
**Pull request by rayphi**
Solves #72 

Contains
- .NET Framework upgrade to v4.7.2
- R# SDK upgrade to 2021.2

### CODE REVIEW

**Comment by rayphi** [comment]
AppVeyor pipeline configuration must be adjusted prior to .NET Framework upgrade  to v4.7.2

**Comment by testcop** [comment]
I thought appveyor would build based on the version in the proj file

**Comment by testcop** [comment]
Do you get unittest failures?

OneTimeSetUp: System.Exception : Can't fetch the list of NuGet versions for JetBrains.Tests.Platform.NETFrameWork
Data:
  NuGet.Source.#1: jb-gallery [http://jb-gallery.azurewebsites.net/api/v2/]
  NuGet.Source.#2: nuget.org [http://www.nuget.org/api/v2/]
  TempDataPath: C:\Users\home.user\AppData\Local\Temp\JetBrains\Cizicib
  Framework: .NETFramework,Version=v4.6.0.0
  RenderedExceptionMessage: Can't fetch the list of NuGet versions for JetBrains.Tests.Platform.NETFrameWork Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  RenderedExceptionDataWtihSensitiveInfo: Can't fetch the list of NuGet versions for JetBrains.Tests.Platform.NETFrameWork Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

--- EXCEPTION #1/3 [FileNotFoundException]
Message = “Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.”
ExceptionPath = Root.InnerException.InnerException
ClassName = System.IO.FileNotFoundException
HResult = COR_E_FILENOTFOUND=E_FILENOTFOUND=WIN32_ERROR_FILE_NOT_FOUND=80070002
Source = NuGet.Protocol
FileNotFound_FileName = “System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”
FileNotFound_FusionLog = “

**Comment by rayphi** [comment]
Yep, solved it now :)

**Comment by testcop** [comment]
great work thanks - just need the version in assembly.cs updating...

**Pull request merged**
