### PR TITLE
Update for R#2018.2

### PR DESCRIPTION
**Pull request by BrunoJuchli**
I've tried making the required changes to update to R# 2018.2.

Now I've got 57 tests failing with

>  The target dispatcher JetDispatcher(:10) does not support asynchronous execution or cross-thread marshalling. Context: "...

I haven't found any relevant information on the net as to what's causing this.

Note: R#2018.2 required a switch from .net 4.5 to 4.6.1 (see https://blog.jetbrains.com/dotnet/2018/03/21/resharper-2018-2-will-require-net-framework-4-6-1/)

Note: Sorry about the unnecessary file changes, I've configured my editor to remove trailing whitespaces at line ends. Didn't notice it until now.

### CODE REVIEW

**Comment by testcop** [comment]
Thanks for starting the next migration. Let the fun begin...I will take a look too.

**Comment by testcop** [comment]
I have it working with a few hacks and need to update a number of classes to inject IShellLocks before I check in

      private static void ExecuteActionOnUiThread(IShellLocks shellLocks, string description, Action fOnExecute)
        {
            shellLocks.ExecuteOrQueueEx(description, fOnExecute);                        
        }

**Comment by testcop** [comment]
Changes made separately and merged. BIG Thanks for your PR but I preferred not to have all the line changes present in the commits...

**Comment by BrunoJuchli** [comment]
@testcop sure thing, next time i'll take better care. It's always a bit difficult with configuring the right editor  settings (.. and I accidentally had the merge tool configured to not show white space changes...)

**Pull request closed without merging**
