### PR TITLE
Upgrade ReSharper SDK to 2017.2

### PR DESCRIPTION
**Pull request by olsh**
Related to #5

### CODE REVIEW

**Comment by testcop** [comment]
Thank you. I will test and merge at the weekend...

**Comment by testcop** [comment]
Hi, 
Compiles okay, tests pass. But I can't get this to install successfully  on VS2015 - it just silently fails on install. Did this branch install within R# okay for you?

**Comment by olsh** [comment]
Hi @testcop,
I tested the version only on VS2017. Will test it on VS2015 tonight.

**Comment by olsh** [comment]
Works on VS2015 as well.
image

Here is my configuration.

**Comment by testcop** [comment]
Branch merge separately with some additional small changes

**Pull request closed without merging**
