### PR TITLE
Recompiled with R# SDK 2021.3.0-eap03 and removed explicit DTE dependencies

### LINKED ISSUE #72: R# 2021.2.x Support
PLEASEEEEEEEEEEEEEEEEEEEEEEEEEEE :) :) :)

https://blog.jetbrains.com/dotnet/2021/08/03/resharper-2021-2-release/

### PR DESCRIPTION
**Pull request by rayphi**
Closes #72 

Contains:

- SDK upgrade to 2021.3.0-eap03
- removed explicit dte dependencies ~to potentially provide backwards compatibility~
- there remains the `Microsoft.VisualStudio.Interop` package which could restore backwards compatibility but this is needed to provide the auto shortcut assignments.

### CODE REVIEW

**Comment by rayphi** [comment]
I think we need to switch to IEnvDteWrapper  like @matkoch  is already doing in the [resharper-presentation-assistant
](https://github.com/JetBrains/resharper-presentation-assistant/commit/2fb6591cdc7dcbaefc024883678376f8e11fdc44) project.

but i have to do some research, because i can't find any alternative for `DTE.Commands.Item()` and `DTE.Windows.Item()`.

**Comment by testcop** [comment]
there might be what we need hanging of IEnvDteWrapper
IEnvDteWrapper::IEnvDteToolWindows::OutputWindow

and a dot peek inside of IEnvDteWrapper::IEnvDteCommands might tell us how to add/change a command

**Comment by rayphi** [comment]
https://youtrack.jetbrains.com/issue/RSRP-486460 seems to be fixed in next version :)

**Comment by rayphi** [comment]
**Update:** _[Issue](https://youtrack.jetbrains.com/issue/RSRP-486460) status changed to_ "Fixed" _and availability to_ "Next EAP 2021.3"

**Comment by testcop** [comment]
Hi @rayphi , what is the latest on this? Are we waiting on Jetbrains before we can support multiple versions of Visual Studio?

**Comment by rayphi** [comment]
Today the version with the bugfixes came out (EAP7) I'll try tomorrow to see if this solves all our problems.

**Comment by ModernRonin** [comment]
does your last commit mean that if I pull your branch and build it, I get a local plugin that works under VS2020 with R# EAP7, @rayphi ?

**Comment by rayphi** [comment]
@ModernRonin yes there are some bugs  on the options page but generally it works fine 😉

**Comment by ModernRonin** [comment]
you are my hero!

**Comment by rayphi** [comment]
@testcop there it is ready to publish 🎉

**Comment by testcop** [comment]
> @testcop there it is ready to publish 🎉

Done Done ? VS2017 onwards? Awesome...

**Comment by rayphi** [comment]
I've tested only VS2019 and VS2022 but  yeah I hope Jetbrains wrappers works also for VS2017

**Comment by rayphi** [comment]
@testcop when do you plan to release this version?

**Comment by testcop** [comment]
released today

**Pull request merged**
